/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.ppojin.simplepoi

import com.ppoijn.simplepoi.SimpleWorkbook
import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new SimpleWorkbook()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
